/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#004e5d',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#76e2ff',
        'error-container': '#ffdad6',
        background: '#f6f8ff',
        'on-secondary-fixed': '#091c35',
        'on-secondary-container': '#51617e',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#edf0ff',
        'tertiary-fixed': '#afecff',
        'secondary-container': '#cdddff',
        'on-error': '#ffffff',
        'surface-tint': '#0c56d0',
        'primary-fixed': '#dae2ff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001848',
        'surface-container': '#e8eeff',
        'on-surface': '#051a3e',
        'outline-variant': '#d5d9e6',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#0040a2',
        'primary-fixed-dim': '#b2c5ff',
        secondary: '#4f5f7b',
        surface: '#ffffff',
        'on-surface-variant': '#434654',
        'secondary-fixed-dim': '#b7c7e8',
        'on-primary': '#ffffff',
        primary: '#003d9b',
        'secondary-fixed': '#d6e3ff',
        tertiary: '#005463',
        'surface-container-high': '#dde6ff',
        'inverse-surface': '#1d3054',
        'on-background': '#051a3e',
        'on-primary-container': '#c4d2ff',
        'surface-container-low': '#f2f5ff',
        'surface-bright': '#faf9ff',
        'tertiary-container': '#007084',
        'inverse-primary': '#b2c5ff',
        'primary-container': '#0a57d6',
        'surface-variant': '#d8e2ff',
        outline: '#737685',
        'surface-container-highest': '#e6ecff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#001f27',
        'surface-dim': '#ccdaff',
        'on-secondary-fixed-variant': '#374763',
        'tertiary-fixed-dim': '#48d7f9',
      },
      fontFamily: {
        headline: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'SF Mono',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '0.875rem',
        full: '9999px',
      },
      keyframes: {
        flowRight: {
          '0%': { left: '0%', opacity: '0' },
          '20%': { opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { left: '100%', opacity: '0' },
        },
      },
      animation: {
        flowRight: 'flowRight 1.5s linear infinite',
      },
    },
  },
  plugins: [],
}

